<?php

/**
 * Metadata version
 */

use OxidEsales\Eshop\Application\Controller\OrderController as OxidOrderController;
use OxidEsales\Eshop\Application\Model\Order;
use OxidEsales\Eshop\Application\Model\PaymentGateway;
use PaymentAG\PaymentModule\Controller\OrderController;
use PaymentAG\PaymentModule\Helper\Config;
use PaymentAG\PaymentModule\Model\OrderExtension;
use PaymentAG\PaymentModule\Model\PaymentGatewayExtension;

$sMetadataVersion = '2.1';

/**
 * Module information
 */
$aModule = [
    'id' => 'paymentag_payment',
    'title' => 'PaymentAG payment module',
    'description' => '',
    'thumbnail' => 'out/pictures/logo.png',
    'version' => '1.0.1',
    'author' => 'PaymentAG',
    'url' => '',
    'email' => '',

    'extend' => [
        PaymentGateway::class => PaymentGatewayExtension::class,
        Order::class => OrderExtension::class,
        OxidOrderController::class => OrderController::class
    ],

    'events' => [
        'onActivate' => '\PaymentAG\PaymentModule\Core\Events::onActivate',
        'onDeactivate' => '\PaymentAG\PaymentModule\Core\Events::onDeactivate',
    ],

    'templates' => [],

    'settings' => [
        [
            'group' => 'main',
            'name' => 'mode',
            'type' => 'select',
            'value' => 'test',
            'constraints' => 'test|live'
        ],
        [
            'group' => 'api',
            'name' => Config::KEY_CLIENTID,
            'type' => 'str',
            'value' => '99999999'
        ],
        [
            'group' => 'api',
            'name' => Config::KEY_SHAREDSECRET,
            'type' => 'str',
            'value' => 'test',
        ],
        [
            'group' => 'api',
            'name' => Config::KEY_APIKEY,
            'type' => 'str',
            'value' => '',
        ],
        [
            'group' => 'behaviour',
            'name' => 'autocapture',
            'type' => 'bool',
            'value' => true
        ],

        [
            'group' => 'behaviour',
            'name' => 'process_cancellations',
            'type' => 'bool',
            'value' => true
        ],
        [
            "group" => "behaviour",
            "name" => Config::KEY_PAYMENT_MODE,
            "type" => 'select',
            'constraints' => 'purchase|reservation',
            'value' => 'purchase'
        ],
        [
            "group" => "behaviour",
            "name" => Config::KEY_CANCEL_MODE,
            "type" => 'select',
            'constraints' => 'delete|cancel',
            'value' => 'cancel'
        ],

        [
            "group" => "internal",
            "name" => Config::KEY_FRONTEND_REQUEST_PARAMS,
            "type" => "arr",
            "value" => array(
                "cl",
                "fnc",
                "onr",
                "stoken",
                "sDeliveryAddressMD5",
                "force_sid",
                "ord_agb",
                "rtoken",
                "clientid",
                "payment",
                "avskey",
                "paymentmode",
                "referenceid",
                "orderid",
                "customerid",
                "referencecustomerid",
                "language",
                "amount",
                "currency",
                "collectionreference",
                "companyname",
                "title",
                "salutation",
                "firstname",
                "lastname",
                "dateofbirth",
                "idcardnumber",
                "street",
                "housenumber",
                "postalcode",
                "city",
                "state",
                "country",
                "phonenumber",
                "emailaddress",
                "deviceid1",
                "deviceid2",
                "ipaddress",
                "bankaccountholder",
                "bankcountry",
                "iban",
                "bic",
                "creditcardnumber",
                "expirationmonth",
                "expirationyear",
                "creditcardtype",
                "cvv",
                "creditcardowner",
                "timeunit",
                "billingcycle",
                "durationperiod",
                "renewalperiod",
                "minimumdurationperiod",
                "maximumdurationperiod",
                "cancellationperiod",
                "trialdurationperiod",
                "trialtimeunit",
                "trialamount",
                "successurl",
                "failurl",
                "backurl",
                "notificationurl",
                "additionaldata",
                "timestamp",
                "delivery-companyname",
                "delivery-salutation",
                "delivery-title",
                "delivery-firstname",
                "delivery-lastname",
                "delivery-street",
                "delivery-housenumber",
                "delivery-postalcode",
                "delivery-city",
                "delivery-state",
                "delivery-country",
                "delivery-phonenumber",
                "delivery-emailaddress",
                "item[x]-id",
                "item[x]-name",
                "item[x]-description",
                "item[x]-quantity",
                "item[x]-totalprice",
                "item[x]-currency",
                "item[x]-taxpercentage",
                "website",
                "layout",
                "relatedinformation-username",
                "relatedinformation-tariff",
                "relatedinformation-tarifftitle",
                "relatedinformation-dateofregistration",
                "relatedinformation-amazonorderreferenceid",
                "relatedinformation-orderdescription",
                "relatedinformation-purpose",
                "relatedinformation-endpointid",
                "relatedinformation-endpointgroupid",
                "relatedinformation-account-accountageindicator",
                "relatedinformation-account-accountlastchangedate",
                "relatedinformation-account-accountlastchangeindicator",
                "relatedinformation-account-accountcreationdate",
                "relatedinformation-account-passwordchangedate",
                "relatedinformation-account-passwordchangeindicator",
                "relatedinformation-account-purchaseslast6months",
                "relatedinformation-account-paymentaccountcreationdate",
                "relatedinformation-account-paymentaccountcreationindicator",
                "relatedinformation-account-addpaymentaccountattemptslast24hours",
                "relatedinformation-account-shippingaddressfirstusagedate",
                "relatedinformation-account-shippingaddressfirstusageindicator",
                "relatedinformation-account-shippingnameindicator",
                "relatedinformation-account-suspiciousactivityindicator",
                "relatedinformation-account-numberofpaymentrequestslast24hours",
                "relatedinformation-account-numberofpaymentrequestslast12months",
                "relatedinformation-account-homephonenumber",
                "relatedinformation-account-mobilephonenumber",
                "relatedinformation-account-workphonenumber",
                "relatedinformation-account-shippingemailaddress",
                "relatedinformation-purchase-transactiontype",
                "relatedinformation-purchase-shippingmethodindicator",
                "relatedinformation-purchase-shippingtimeframe",
                "relatedinformation-purchase-preorderavailabilitydate",
                "relatedinformation-purchase-preorderavailabilityindicator",
                "relatedinformation-purchase-reorderitemsindicator",
                "relatedinformation-purchase-prepaidandgiftcardamount",
                "relatedinformation-purchase-prepaidandgiftcardcurrency",
                "relatedinformation-purchase-prepaidandgiftcardcount",
                "relatedinformation-browser-acceptheader",
                "relatedinformation-browser-useragentheader",
                "relatedinformation-browser-language",
                "relatedinformation-browser-timezoneoffset",
                "relatedinformation-browser-javaenabled",
                "relatedinformation-browser-javascriptenabled",
                "relatedinformation-browser-screenwidth",
                "relatedinformation-browser-screenheight",
                "relatedinformation-browser-colordepth",
                "relatedinformation-browser-challengewindowsize",
                "relatedinformation-authentication-authenticationdata",
                "relatedinformation-authentication-authenticationmethod",
                "relatedinformation-authentication-authenticationtimestamp",
                "relatedinformation-authentication-priorauthenticationdata",
                "relatedinformation-authentication-priorauthenticationmethod",
                "relatedinformation-authentication-priorauthenticationtimestamp",
                "relatedinformation-authentication-priorauthenticationreference",
            ),
        ],
        [
            "group" => "internal",
            "name" => Config::KEY_FRONTEND_SUCCESS_PARAMS,
            "type" => "arr",
            "value" => array(
                "clientid",
                "transactionid",
                "referenceid",
                "subscriptionid",
                "amount",
                "currency",
                "paymentmethod",
                "customerid",
                "transactionstatus",
                "transactionstatusaddition",
                "creditcardtype",
                "providertransactionid",
                "providerpurpose",
                "additionaldata",
                "timestamp",
            ),
        ],
        [
            "group" => "internal",
            "name" => Config::KEY_FRONTEND_ERROR_PARAMS,
            "type" => "arr",
            "value" => array(
                "clientid",
                "referenceid",
                "errornumber",
                "errortext",
                "additionaldata",
                "timestamp",
            ),
        ]
    ]
];
