<?php

namespace PaymentAG\PaymentModule\Helper;

class Vars {

    const TRANSACTION_STATUS_OK = 'OK';
    const TRANSACTION_STATUS_PENDING = 'PAYMENT_PENDING';
    const TRANSACTION_STATUS_FAILED = 'ERROR';
    const TRANSACTION_STATUS_NOT_FINISHED = 'NOT_FINISHED';

    const PAYMENT_STATUS_OK = 'OK';
    const PAYMENT_STATUS_STARTED = 'STARTED';
    const PAYMENT_STATUS_PAYED = 'PAYED';
    const PAYMENT_STATUS_CANCELED = 'CANCELED';
    const PAYMENT_STATUS_PENDING = 'PENDING';
    const PAYMENT_STATUS_FAILED = 'FAILED';

    const ORDER_COLUMN_PAYMENT_DETAILS = "PAGPAYMENTDETAILS";
    const ORDER_COLUMN_PAYMENT_STATUS = "PAGPAYMENTSTATUS";
}